name: CI - Next.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./fashion-ecommerce
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cài Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          working-directory: ./fashion-ecommerce

      # 3. Cài dependency
      - name: Install dependencies
        run: npm install

      # 4. Chạy lint (nếu có script "lint" trong package.json)
      - name: Run lint
        run: npm run lint
        continue-on-error: false

      # 5. Chạy test (nếu bạn có "test")
      - name: Run tests
        run: npm test
        continue-on-error: false

      # 6. Build Next.js
      - name: Build Next.js
        run: npm run build
